# Generated by Django 3.2.6 on 2021-09-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movieshots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='movies.movieshoots', verbose_name='Кадры из фильма'),
        ),
    ]
